config/routes.rb
Rails.application.routes.draw do

  root 'portfolios#index'
  resources :portfolios do
    resources :stocks, only: [:update, :create, :destroy, :edit]
  end
  resource :refresher, only: :update

end

app/models/portfolio.rb
class Portfolio < ActiveRecord::Base
  has_many :stocks

  def total_value
    value = 0
    self.stocks.all.each do |stock|
      value += stock.amount*stock.price
    end
    value.round(2)
  end
end

app/models/stock.rb
class Stock < ActiveRecord::Base
  validates :amount, numericality: { only_integer: true }
  belongs_to :portfolios
end

app/models/stock_api.rb
require 'rubygems'
require 'stock_quote'
class StockApi
  attr_reader :stock
  def initialize(symbol)
    @stock = StockQuote::Stock.json_quote(symbol)
  end


  def stock_params
    s = @stock["quote"]
    {symbol: s["symbol"], name: s["Name"], price: s["Ask"], change: s["ChangeinPercent"].to_f, high: s["DaysHigh"], low: s["DaysLow"]}
  end

  def check_stock?
    @stock["quote"]["Name"]
  end

  def multi_stock_params
    all_stocks = []
    @stock["quote"].each do |s|
      all_stocks << {symbol: s["symbol"], name: s["Name"], price: s["Ask"], change: s["ChangeinPercent"].to_f, high: s["DaysHigh"], low: s["DaysLow"]}
    end
    all_stocks
  end
end

app/models/stock_creator.rb
class StockCreator

  def initialize(stock, portfolio_id, amount)
    @stock = stock.upcase
    @amount = amount.to_i
    @portfolio_id = portfolio_id
  end

  def update_existing
    if stock = existing_stock
      total = stock.amount.to_i + @amount
      stock.update(amount: total)
      return true
    end
    false
  end

  def existing_stock
    p = Portfolio.find(@portfolio_id)
    p.stocks.find_by symbol: @stock
  end
end

app/models/stock_refresher.rb
class StockRefresher
  class << self
    def refresh_all
      sapi = StockApi.new(all_symbols)
      sapi.multi_stock_params.each do |stock|
        current_stocks = Stock.where symbol: stock[:symbol]
        current_stocks.each do |s|
          s.update(stock)
        end
      end
    end


    def all_symbols
      symbols = []
      Stock.all.each do |stock|
        symbols << stock.symbol
      end
      symbols.uniq
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  include PortfoliosHelper
  def index
    @portfolios = Portfolio.all
  end

  def new
    @portfolio = Portfolio.new
  end

  def create
    @portfolio = Portfolio.new(portfolio_params)
    if @portfolio.save
      flash[:success] = "Portfolio '#{@portfolio.name}' Created!"
      redirect_to @portfolio
    else
      flash.now[:alert] = "Portfolio not created!"
      render :edit
    end
  end

  def show
    @portfolio = Portfolio.find(params[:id])
  end

  def edit
    @portfolio = Portfolio.find(params[:id])
    @stock = Stock.new
    @stock.portfolio_id = @portfolio.id
  end

  def update
    @portfolio = Portfolio.find(params[:id])
    if @portfolio.update(portfolio_params)
      flash[:success] = "'#{@portfolio.name}' Updated!"
      redirect_to @portfolio
    else
      flash.now[:alert] = "Portfolio not updated!"
      render :edit
    end
  end

  def destroy
    @portfolio = Portfolio.find(params[:id])
    if @portfolio.destroy
      flash[:success] = "'#{@portfolio.name}' Deleted!"
    else
      flash[:alert] = "Portfolio not deleted!"
    end
    redirect_to portfolios_path
  end


  private

  def portfolio_params
    params.require(:portfolio).permit(:name)
  end

end

app/controllers/refreshers_controller.rb
class RefreshersController < ApplicationController

  def update
    StockRefresher.refresh_all
    redirect_to portfolios_path
  end

end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController


  def create
    sym = params[:stock][:symbol]
    amount = params[:stock][:amount]
    @portfolio = Portfolio.find(params[:portfolio_id])
    stock_creator = StockCreator.new(sym, params[:portfolio_id], amount)
    if stock_creator.update_existing
      redirect_to portfolio_path(params[:portfolio_id])
    else
      sapi = StockApi.new(sym)
      if sapi.check_stock?
        @stock = Stock.new(merged_params(sapi.stock_params))
        @stock.portfolio_id = params[:portfolio_id]
        @stock.save ? flash[:success] = "#{@stock.name} added!" : flash[:alert] = "Invalid Input!"
        redirect_to portfolio_path(params[:portfolio_id])
      else
        flash[:alert] = "Stock not found!"
        redirect_to edit_portfolio_path(params[:portfolio_id])
      end
    end
  end

  def edit
    @portfolio = Portfolio.find(params[:portfolio_id])
    @stock = Stock.find(params[:id])
  end

  def update
    @stock = Stock.find(params[:id])
    if @stock.update(amount: params[:stock][:amount])
      flash[:success] = "#{@stock.name} added!"
      redirect_to portfolio_path(@stock[:portfolio_id])
    else
      @portfolio = Portfolio.find(params[:portfolio_id])
      flash[:alert] = "Invalid Input!"
      render :edit
    end
  end

  def destroy
    @stock = Stock.find(params[:id])
    if @stock.destroy
      flash[:success] = "'#{@stock.name}' Deleted!"
    else
      flash[:alert] = "stock not deleted!"
    end
    redirect_to portfolio_path(params[:portfolio_id])
  end

  private

  def merged_params(hash)
    hash.merge({amount: params[:stock][:amount]})
  end
  def white_listed
    params.require(:stock).permit(:id, :portfolio_id, :amount)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def all_portfolio_value
    total = 0
    Portfolio.all.each { |folio| total += folio.total_value }
    total.round(2)
  end

end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/helpers/refreshers_helper.rb
module RefreshersHelper
end

app/helpers/stocks_helper.rb
module StocksHelper

  def total_value(stock)
    (stock.price*stock.amount).round(2)
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stocks</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

</head>
<body>
  <div class="container">
  <% flash.each do |key, value| %>
    <%= content_tag :div, value, class: "flash #{key}" %>
  <% end %>

  <%= yield %>
  </div>
</body>
  <footer class="footer">
    <div class="container">
    <h4>
      <%= link_to "Index", portfolios_path %>
    </h4>
  </div class="container">
  </footer>
</html>

app/views/portfolios/_form.html.erb
<%= form_for @portfolio do |p| %>
<p>
  <br>
  <%= p.text_field :name %>
  <%= p.submit "Set Name"%>
</p>
<% end %>

app/views/portfolios/edit.html.erb
<%= render './stocks/form' %>

app/views/portfolios/index.html.erb
<h1>
    Stocky &#128480;
</h1>

<% if @portfolios%>
<h3>&#128176;: $<%=all_portfolio_value%></h3>

<ul>
<% @portfolios.each do |portfolio| %>
    <li>
        <span class="stock"><%= link_to portfolio.name, portfolio_path(portfolio) %></span> &nbsp;
        <span class="value">=> $<%= portfolio.total_value%></span><br>
        <span class="delete"><%= link_to "delete", portfolio_path(portfolio), method: :delete, data: {confirm: "Are you sure?"} %></span>
    </li>
    <hr>
<% end %>
</ul>
<% end %>

<%= form_tag({controller: "refreshers", action: "update"}, method: "patch") do%>
  <%= submit_tag("Refresh All Stocks") %>
<% end %>

<%= link_to "New Portfolio", new_portfolio_path %>

app/views/portfolios/new.html.erb
<div class="container">
<%= render 'form' %>
</div>

app/views/portfolios/show.html.erb
<h1><%= @portfolio.name %></h1>
<%= render 'form' %>

<h3>Portfolio Value: $<%= @portfolio.total_value%></h3>
<br>
<%= render partial: 'stocks/stock', collection: @portfolio.stocks %>
<br>
<%= link_to "add stock", edit_portfolio_path %>

app/views/stocks/_form.html.erb
<h3>Stock</h3>
<% if @stock %>
  <%= form_for [ @portfolio, @stock ] do |f| %>
    <p>
      <%= f.label :symbol, "Symbol"  %>
  <br/>
      <%= f.text_field :symbol %>
    </p>
    <p>
      <%= f.label :amount, "Number of stock" %><br/>
      <%= f.text_field :amount %>
    </p>
    <p>
      <%= f.submit 'Submit' %>
    </p>
  <% end %>
<% end %>

app/views/stocks/_stock.html.erb
<div class="stock-display">
  <h4><%= stock.name %></h4>
  <span>Symbol: <%= stock.symbol %></span>
  <span>Amount: <%= stock.amount %></span>
  <span>Price: $<%= stock.price %></span>
  <br>
  <span>Net Value: $<%= total_value(stock) %></span>
  <span>Change: <%= stock.change %>%</span>
  <span>High: <%= stock.high %></span>
  <span>Low: <%= stock.low %></span>
  <br>
  <%= link_to "edit amount", edit_portfolio_stock_path(portfolio_id: stock[:portfolio_id], id: stock[:id])%> |
  <span class="delete"><%= link_to "delete", portfolio_stock_path(portfolio_id: stock[:portfolio_id], id: stock[:id]), method: :delete, data: {confirm: "Are you sure?"}%></span>
</div>

app/views/stocks/edit.html.erb
<%= form_for [ @portfolio, @stock ] do |f| %>
  <p>
    <%= f.label :amount, "Adjust amount" %><br/>
    <%= f.text_field :amount %>
  </p>
  <p>
    <%= f.submit 'Submit' %>
  </p>
<% end %>